config/routes.rb
Aps::Application.routes.draw do
  root :to => 'member_zone#index'

  resources :application_processes
  resources :application_form_fields
  resources :application_forms do
    member do
      get :apply
    end
  end
  resources :form_fields
  resources :forms do
    member do
      get :apply
    end
  end
  resources :users

  match ':controller(/:action(/:id))(.:format)'
end

app/controllers/application_processes_controller.rb
class ApplicationProcessesController < ApplicationController
  before_filter :confirm_login
  layout :specified_layout
  # GET /application_processes
  # GET /application_processes.json
  def index
    @application_processes = ApplicationProcess.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @application_processes }
    end
  end

  # GET /application_processes/1
  # GET /application_processes/1.json
  def show
    @application_process = ApplicationProcess.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @application_process }
    end
  end

  # GET /application_processes/new
  # GET /application_processes/new.json
  def new
    @application_process = ApplicationProcess.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @application_process }
    end
  end
  
  def reject
    @application = ApplicationForm.find(params[:id])
    @application_process = ApplicationProcess.new(:application_form_id => params[:id], :refferer_id => session[:user_id], :status => 111, :reffer_to_id => @application.user_id, :last_process_id => params[:pid])
  end
  
  def approve
    @application = ApplicationForm.find(params[:id])
    @application_process = ApplicationProcess.new(:application_form_id => params[:id], :refferer_id => session[:user_id], :status => 10, :reffer_to_id => @application.user_id, :last_process_id => params[:pid])
  end
  
  def forward
    @application = ApplicationForm.find(params[:id])
    @application_process = ApplicationProcess.new(:application_form_id => params[:id], :refferer_id => session[:user_id], :last_process_id => params[:pid])
  end

  # GET /application_processes/1/edit
  def edit
    @application_process = ApplicationProcess.find(params[:id])
  end

  # POST /application_processes
  # POST /application_processes.json
  def create
    @application_process = ApplicationProcess.new(params[:application_process])
    last_process_id = params[:application_process][:last_process_id]
    unless last_process_id.blank?
      last_process = ApplicationProcess.find(last_process_id)
      if last_process
        last_process.update_attributes(:status => 5)
      end
    end

    respond_to do |format|
      if @application_process.save
        format.html { redirect_to @application_process, notice: "Application process was successfully created." }
        format.json { render json: @application_process, status: :created, location: @application_process }
      else
        format.html { render action: "new" }
        format.json { render json: @application_process.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /application_processes/1
  # PUT /application_processes/1.json
  def update
    @application_process = ApplicationProcess.find(params[:id])

    respond_to do |format|
      if @application_process.update_attributes(params[:application_process])
        format.html { redirect_to @application_process, notice: 'Application process was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @application_process.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /application_processes/1
  # DELETE /application_processes/1.json
  def destroy
    @application_process = ApplicationProcess.find(params[:id])
    @application_process.destroy

    respond_to do |format|
      format.html { redirect_to application_processes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_processes_helper.rb
module ApplicationProcessesHelper
end

app/views/application_processes/_form.html.erb
<%= simple_form_for @application_process, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :application_form_id, :as => :hidden %>
  <%= f.input :refferer_id, :as => :hidden %>
  <%= f.input :status, :as => :hidden %>
  <%= f.input :reffer_to_id, :as => :hidden %>
  <% f.association :reffer_to, :label => "Forward To" %>
  <%= f.input :purpose %>
  <%= f.input :message, :input_html => {:size => "60x6"} %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                application_processes_path, :class => 'btn' %>
  </div>
<% end %>

app/views/application_processes/approve.html.erb
<%- model_class = ApplicationProcess -%>
<div class="page-header">
  <h1>Approve: <%= @application.form.title%></h1>
</div>
<%= simple_form_for @application_process, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :application_form_id, :as => :hidden %>
  <%= f.input :refferer_id, :as => :hidden %>
  <%= f.input :last_process_id, :as => :hidden %>
  <%= f.input :status, :as => :hidden %>
  <%= f.input :reffer_to_id, :as => :hidden %>
  <% f.association :reffer_to, :label => "Forward To" %>
  <%= f.input :purpose %>
  <%= f.input :message, :input_html => {:size => "60x6"} %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                application_processes_path, :class => 'btn' %>
  </div>
<% end %>

app/views/application_processes/edit.html.erb
<%- model_class = ApplicationProces -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/application_processes/forward.html.erb
<%- model_class = ApplicationProcess -%>
<div class="page-header">
  <h1>Forward: <%= @application.form.title%></h1>
</div>
<%= simple_form_for @application_process, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :application_form_id, :as => :hidden %>
  <%= f.input :refferer_id, :as => :hidden %>
  <%= f.input :last_process_id, :as => :hidden %>
  <%= f.input :status, :as => :hidden %>
  <%= f.association :reffer_to, :collection => User.where(:role => [5, 10]), :label => "Forward To" %>
  <%= f.input :purpose %>
  <%= f.input :message, :input_html => {:size => "60x6"} %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                application_processes_path, :class => 'btn' %>
  </div>
<% end %>

app/views/application_processes/index.html.erb
<%- model_class = ApplicationProcess -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:application_form_id) %></th>
      <th><%= model_class.human_attribute_name(:refferer_id) %></th>
      <th><%= model_class.human_attribute_name(:reffer_to_id) %></th>
      <th><%= model_class.human_attribute_name(:purpose) %></th>
      <th><%= model_class.human_attribute_name(:message) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @application_processes.each do |application_process| %>
      <tr>
        <td><%= link_to application_process.id, application_process_path(application_process) %></td>
        <td><%= application_process.application_form_id %></td>
        <td><%= application_process.refferer_id %></td>
        <td><%= application_process.reffer_to_id %></td>
        <td><%= application_process.purpose %></td>
        <td><%= application_process.message %></td>
        <td><%= application_process.status %></td>
        <td><%=l application_process.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_application_process_path(application_process), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      application_process_path(application_process),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_application_process_path,
            :class => 'btn btn-primary' %>

app/views/application_processes/new.html.erb
<%- model_class = ApplicationProcess -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/application_processes/reject.html.erb
<%- model_class = ApplicationProcess -%>
<div class="page-header">
  <h1>Reject: <%= @application.form.title%></h1>
</div>
<%= simple_form_for @application_process, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :application_form_id, :as => :hidden %>
  <%= f.input :refferer_id, :as => :hidden %>
  <%= f.input :last_process_id, :as => :hidden %>
  <%= f.input :status, :as => :hidden %>
  <%= f.input :reffer_to_id, :as => :hidden %>
  <% f.association :reffer_to, :label => "Forward To" %>
  <%= f.input :purpose %>
  <%= f.input :message, :input_html => {:size => "60x6"} %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                application_processes_path, :class => 'btn' %>
  </div>
<% end %>

app/views/application_processes/show.html.erb
<%- model_class = ApplicationProcess -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>
Application has been Processed

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              application_processes_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_application_process_path(@application_process), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              application_process_path(@application_process),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>